### ISSUE TITLE
Get exception when size of job output is 0 bytes long.

### ISSUE THREAD

**Issue by andrepacak** [boalang/drupal-service#1]
When I try to access the output of a job which is 0 bytes long via the method getOutput of the class JobHandle I get the following exception:

Exception in thread "main" edu.iastate.cs.boa.BoaException: Access denied for user <username>
	at edu.iastate.cs.boa.BoaClient.getOutputSize(BoaClient.java:743)
	at edu.iastate.cs.boa.JobHandle.getOutputSize(JobHandle.java:267)
...
Caused by: org.apache.xmlrpc.XmlRpcException: Access denied for user <username>
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at edu.iastate.cs.boa.BoaClient.execute(BoaClient.java:152)
	at edu.iastate.cs.boa.BoaClient.execute(BoaClient.java:144)
	at edu.iastate.cs.boa.BoaClient.getOutputSize(BoaClient.java:741)
	... 10 more

This also happens when I use the method getOutputSize.

**Comment by psybers** [comment]
This actually makes some sense, based on how Drupal handles job outputs. Drupal has a check to see if there is actually output.  I think 'access denied' is a strange way of indicating there is no output, but that is what it's doing.

So probably the API should be expanded a bit and add a function to test if there is output and then the `getOutput` and `getOutputSize` methods would simply have `hasOutput()` as a pre-req.  Or perhaps return `0` size and empty string if there is no output.

**Comment by psybers** [comment]
So the client API itself is fine.  This needed a fix on the server-side API so I moved the issue to a new project.  This should be fixed by 1bb3f9d8219093f06c29cd7b4de43e57df1ae394.
